### ISSUE TITLE
Enable Interrupts instead of busywaiting

### ISSUE THREAD

**Issue by tperale** [tperale/sx127x#1]
Busywaiting for an interrupt on the pin DI0,DI1,DI2,DI3 introduce some delay in the software. As we can see in the next picture, the time between the interrupt and the acknowledgement from the software can almost reach 1ms.

![DS1Z_QuickPrint5](https://user-images.githubusercontent.com/4118134/95308388-2093d380-088a-11eb-80cb-69abd7c077ab.png)

If we assign some pins from the RE-MOTE to handle the interrupts we could process the pending packet more quickly.

So far only two pins are used by the driver.

- DI0 acknowledge a completed transmition on TX side and acknowledge a pending packet on RX side
- DI3 acknowledge an ongoing packet reception

The following code could be used to process the interrupt on those two pins.

```
static void sx1272_interrupt_dio0() { 
  if (__sx1272_dev.mode == sx1272_mode_receiver 
      || __sx1272_dev.mode == sx1272_mode_receiver_single) {
    SX1272_DEV.rx_timestamp = RTIMER_NOW();
    sx1272_rx_internal_set(&__sx1272_dev, sx1272_rx_received);
    sx1272_write_register(__sx1272_dev.spi, REG_LR_IRQFLAGS, RFLR_IRQFLAGS_RXDONE);
  } else if (__sx1272_dev.mode == sx1272_mode_transmitter) {
    sx1272_write_register(__sx1272_dev.spi, REG_LR_IRQFLAGS, RFLR_IRQFLAGS_TXDONE);
    sx127x_set_opmode(&SX1272_DEV, sx1272_mode_standby);
  }
}
static void sx1272_interrupt_dio1() { 
  sx1272_write_register(__sx1272_dev.spi, REG_LR_IRQFLAGS, RFLR_IRQFLAGS_RXTIMEOUT);
}
static void sx1272_interrupt_dio3() { 
  if (__sx1272_dev.mode == sx1272_mode_receiver 
      || __sx1272_dev.mode == sx1272_mode_receiver_single) {
    SX1272_DEV.receiv_timestamp = RTIMER_NOW();
    sx1272_rx_internal_set(&__sx1272_dev, sx1272_rx_receiving);
    sx1272_write_register(__sx1272_dev.spi, REG_LR_IRQFLAGS, RFLR_IRQFLAGS_VALIDHEADER);
  }
}
```

## TODO

- [x] Assign pins that will handle the interrupts
- [x] Setup interrupt in Contiki
- [x] Do the timestamping inside the interrupts
- [x] Handle both with or without interrupt usage of the driver.

**Comment by tperale** [comment]
The following line would need to be removed.

https://github.com/tperale/sx127x/blob/b74c17f54f8becf2ad0626154c011f90b1bd2ebd/src/sx1272.c#L427

**Comment by tperale** [comment]
The branch https://github.com/tperale/sx127x/tree/interrupt-support is WIP. Still need to configure the pins

**Comment by tperale** [comment]
This issue is mandatory to enable CSMA support
